require "json"
require "csv"

school_districts_file = File.read("data/districts_w_feature_data2015.geojson")
school_districts_data = JSON.parse(school_districts_file)


school_districts_data["features"].each do |district|
  district["properties"].delete("DPETWHIP")
  district["properties"].delete("DPETWHIV")
  district["properties"].delete("DPETSPEP")
  district["properties"].delete("DPETASIV")
  district["properties"].delete("DPETASIP")
  district["properties"].delete("DPETSPEV")
  district["properties"].delete("DPETALLC")
  district["properties"].delete("DPETINDP")
  district["properties"].delete("Shape_Leng")
  district["properties"].delete("NCES_DISTR")
  district["properties"].delete("DPETINDV")
  district["properties"].delete("DPETTWOP")
  district["properties"].delete("DPETHISP")
  district["properties"].delete("DPETHISV")
  district["properties"].delete("DPETTWOV")
  district["properties"].delete("DPETBLAV")
  district["properties"].delete("DPETBLAP")
  district["properties"].delete("DPETPCIV")
  district["properties"].delete("DPETECOP")
  district["properties"].delete("DPETECOV")
  district["properties"].delete("DPETPCIP")
  district["properties"].delete("OSSFischerBlack")
  district["properties"].delete("OSSPercentBlack")
  district["properties"].delete("OSSFischerAmericanIndian")
  district["properties"].delete("OSSPercentAmericanIndian")
  district["properties"].delete("OSSPercentAmericanIndian")
  district["properties"].delete("OSSFischerAsian")
  district["properties"].delete("OSSPercentAsian")
  district["properties"].delete("OSSFischerLatino")
  district["properties"].delete("OSSPercentLatino")
  district["properties"].delete("OSSFischerPacific")
  district["properties"].delete("OSSPercentPacific")
  district["properties"].delete("OSSFischerMulti")
  district["properties"].delete("OSSPercentMulti")
  district["properties"].delete("OSSFischerWhite")
  district["properties"].delete("OSSPercentWhite")
  district["properties"].delete("OSSFischerEconDis")
  district["properties"].delete("OSSPercentEconDis")
  district["properties"].delete("OSSFischerSpecialEdu")
  district["properties"].delete("OSSPercentSpecialEdu")
  district["properties"].delete("AltEduFischerBlack")
  district["properties"].delete("AltEduPercentBlack")
  district["properties"].delete("AltEduFischerAmericanIndian")
  district["properties"].delete("AltEduPercentAmericanIndian")
  district["properties"].delete("AltEduFischerAsian")
  district["properties"].delete("AltEduPercentAsian")
  district["properties"].delete("AltEduFischerLatino")
  district["properties"].delete("AltEduPercentLatino")
  district["properties"].delete("AltEduFischerPacific")
  district["properties"].delete("AltEduPercentPacific")
  district["properties"].delete("AltEduFischerMulti")
  district["properties"].delete("AltEduPercentMulti")
  district["properties"].delete("AltEduFischerWhite")
  district["properties"].delete("AltEduPercentWhite")
  district["properties"].delete("AltEduFischerEconDis")
  district["properties"].delete("AltEduPercentEconDis")
  district["properties"].delete("AltEduFischerSpecialEdu")
  district["properties"].delete("AltEduPercentSpecialEdu")
  district["properties"].delete("OSSCountBlack")
  district["properties"].delete("OSSCountAmericanIndian")
  district["properties"].delete("OSSCountAsian")
  district["properties"].delete("OSSCountLatino")
  district["properties"].delete("OSSCountPacific")
  district["properties"].delete("OSSCountMulti")
  district["properties"].delete("OSSCountWhite")
  district["properties"].delete("OSSCountEconDis")
  district["properties"].delete("OSSCountSpecialEdu")
  district["properties"].delete("AltEduCountBlack")
  district["properties"].delete("AltEduCountAmericanIndian")
  district["properties"].delete("AltEduCountAsian")
  district["properties"].delete("AltEduCountLatino")
  district["properties"].delete("AltEduCountPacific")
  district["properties"].delete("AltEduCountMulti")
  district["properties"].delete("AltEduCountWhite")
  district["properties"].delete("AltEduCountEconDis")
  district["properties"].delete("AltEduCountSpecialEdu")
end

puts school_districts_data["features"][0]["properties"]

# export as json
File.open("geojson/base_districts.geojson", "w") do |file|
  file.puts school_districts_data.to_json
end
